# 3.1 Exception을 갖춘 DAO
* JDBC에서 데이터베이스와 연결 시 Pool 방식을 이용하는데 제한된 이용 가능한 Connection과 PreparedStatement를 보유하고 있다. 이 제한된 리소스를 이용한 후 close()라는 메소드로 반환을 해야한다. 반환이 안되어 Pool로 돌아가지 않는 리소스가 누적될 경우 서버가 그 후에 들어오는 프로세스를 감당하지 못하고 치명적인 오류를 내며 서버 작동이 중단 될 수 있다

```java
public int getCount() throws SQLException {
	Connection c = null;
	PreparedStatement ps = null;
	ResultSet rs = null;

	try {
		c = dataSource.getConnection();

		ps = c.prepareStatement("select count(*) from users");

		rs= ps.executeQuery();
		rs.next();
		return rs.getInt(1);
	} catch(SQLException e) {
		throw e;
	} finally {
		if(rs != null) {
			try {
				rs.close();
			} catch (SQLException e) {
			}
		}
		if(ps != null) {
			try {
				ps.close();
			} catch (SQLException e) {
			}
		}
		if(c != null) {
			try {
				c.close();
			} catch (SQLException e) {
			}
		}
	}
}
```
* close()에서도 에러가 날 수 있으므로 try/catch로 감싸준다
* close()는 만들어진 반대의 순서로 실행해준다
* SQLException이 감싸고 있어 try/catch가 필요 없어 보일 수 있으나 rs/ps의 close()에서 에러가 나면 나머지 close() 작업을 생략할 수 있어 꼭 필요하다
